### IMPORT LIBRARY

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

### LOAD DATA

In [3]:
DATA_DIR = Path("../data/raw")

def load_table(filename: str) -> pd.DataFrame:
    df = pd.read_csv(DATA_DIR / filename)
    print(f"{filename}: {df.shape[0]} rows, {df.shape[1]} cols")
    return df

clients     = load_table("clients.csv")
campaigns   = load_table("campaigns.csv")
ad_spend    = load_table("ad_spend.csv")
leads       = load_table("leads.csv")
conversions = load_table("conversions.csv")

clients.csv: 50 rows, 8 cols
campaigns.csv: 500 rows, 10 cols
ad_spend.csv: 3000 rows, 10 cols
leads.csv: 2500 rows, 8 cols
conversions.csv: 400 rows, 7 cols

### DATA UNDERSTANDING

##### 1. Clients Dataset

In [4]:
clients.head()

,client_id,company_name,industry,monthly_budget_idr,contract_start,contract_status,account_manager,city
0,CLT001,PT Properti Global,Property,96000000,2022-10-07,paused,Reza Hartono,Surabaya
1,CLT002,PT Estat Prima,Property,87000000,2023-07-29,paused,Maya Permana,Jakarta
2,CLT003,PT Bayar Mandiri,Fintech,100000000,2024-02-24,active,Putri Wijaya,Semarang
3,CLT004,CV Maju Prima,FMCG,79000000,2023-03-29,active,Hendra Nugroho,Jakarta
4,CLT005,PT Trend Sentral,Fashion E-commerce,68000000,2021-07-06,active,Dewi Lestari,Jakarta

In [5]:
clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   client_id           50 non-null     object
 1   company_name        50 non-null     object
 2   industry            50 non-null     object
 3   monthly_budget_idr  50 non-null     int64
 4   contract_start      50 non-null     object
 5   contract_status     50 non-null     object
 6   account_manager     50 non-null     object
 7   city                50 non-null     object
dtypes: int64(1), object(7)
memory usage: 3.3+ KB

In [6]:
# Check Data Quality
clients.isnull().sum()

client_id             0
company_name          0
industry              0
monthly_budget_idr    0
contract_start        0
contract_status       0
account_manager       0
city                  0
dtype: int64

In [7]:
clients.duplicated().sum()

np.int64(0)

##### 2. Campaigns Dataset

In [8]:
campaigns.head()

,campaign_id,client_id,campaign_name,channel,start_date,end_date,budget_idr,actual_spend_idr,objective,status
0,CAM0001,CLT029,Harbolnas 2023,Instagram,2023-06-02,2023-08-16,12000000,12173077,lead_gen,completed
1,CAM0002,CLT005,Brand Awareness Q4,Facebook,2022-11-07,2022-12-10,41000000,42632830,traffic,active
2,CAM0003,CLT008,Independence Day 2023,YouTube,2023-04-08,2023-06-27,29000000,27262983,conversions,completed
3,CAM0004,CLT038,New Year Campaign 2022,TikTok,2022-05-04,2022-05-30,18000000,17551854,awareness,completed
4,CAM0005,CLT011,Conversion Boost 2022,IG,2022-06-03,2022-07-07,5000000,4658517,app_installs,completed

In [9]:
campaigns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   campaign_id       500 non-null    object
 1   client_id         500 non-null    object
 2   campaign_name     500 non-null    object
 3   channel           500 non-null    object
 4   start_date        500 non-null    object
 5   end_date          500 non-null    object
 6   budget_idr        500 non-null    int64
 7   actual_spend_idr  500 non-null    int64
 8   objective         500 non-null    object
 9   status            500 non-null    object
dtypes: int64(2), object(8)
memory usage: 39.2+ KB

In [27]:
campaigns['channel'].unique()

array(['Instagram', 'Facebook', 'YouTube', 'TikTok', 'IG', 'LinkedIn',
       'Google', 'instagram'], dtype=object)

In [10]:
campaigns.isnull().sum()

campaign_id         0
client_id           0
campaign_name       0
channel             0
start_date          0
end_date            0
budget_idr          0
actual_spend_idr    0
objective           0
status              0
dtype: int64

In [11]:
campaigns.duplicated().sum()

np.int64(0)

##### 3. Advertisement Spend Dataset

In [12]:
ad_spend.head()

,spend_id,campaign_id,spend_date,impressions,clicks,conversions,spend_idr,cpm,cpc,ctr
0,SPD00001,CAM0001,2023-06-11,25738,232,5.0,2644074,102730,11397,0.0090
1,SPD00002,CAM0001,2023-07-06,163698,3456,96.0,3246447,19832,939,0.0211
2,SPD00003,CAM0001,2023-08-16,141560,4124,71.0,393786,2782,95,0.0291
3,SPD00004,CAM0001,2023-06-18,195781,2127,84.0,871631,4452,410,0.0109
4,SPD00005,CAM0001,2023-06-28,48754,727,NaN,4169370,85519,5735,0.0149

In [13]:
ad_spend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   spend_id     3000 non-null   object
 1   campaign_id  3000 non-null   object
 2   spend_date   3000 non-null   object
 3   impressions  3000 non-null   int64
 4   clicks       3000 non-null   int64
 5   conversions  2687 non-null   float64
 6   spend_idr    3000 non-null   int64
 7   cpm          3000 non-null   int64
 8   cpc          3000 non-null   int64
 9   ctr          3000 non-null   float64
dtypes: float64(2), int64(5), object(3)
memory usage: 234.5+ KB

In [14]:
ad_spend.isnull().sum()

spend_id         0
campaign_id      0
spend_date       0
impressions      0
clicks           0
conversions    313
spend_idr        0
cpm              0
cpc              0
ctr              0
dtype: int64

In [15]:
ad_spend.duplicated().sum()

np.int64(0)

##### 4. Leads Dataset

In [16]:
leads.head()

,lead_id,campaign_id,client_id,created_date,status,lead_score,city,acquisition_channel
0,LED00001,CAM0490,CLT025,2024-01-18,contacted,44,Semarang,Website
1,LED00002,CAM0425,CLT007,2024-06-13,new,58,Balikpapan,Instagram
2,LED00003,CAM0289,CLT047,2022-11-10,new,76,Semarang,NaN
3,LED00004,CAM0432,CLT001,2022-11-04,qualified,47,Medan,Google
4,LED00005,CAM0086,CLT024,2024-05-11,converted,86,Malang,NaN

In [17]:
leads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   lead_id              2500 non-null   object
 1   campaign_id          2500 non-null   object
 2   client_id            2500 non-null   object
 3   created_date         2500 non-null   object
 4   status               2500 non-null   object
 5   lead_score           2500 non-null   int64
 6   city                 2500 non-null   object
 7   acquisition_channel  1990 non-null   object
dtypes: int64(1), object(7)
memory usage: 156.4+ KB

In [18]:
leads.isnull().sum()

lead_id                  0
campaign_id              0
client_id                0
created_date             0
status                   0
lead_score               0
city                     0
acquisition_channel    510
dtype: int64

In [19]:
leads.duplicated().sum()

np.int64(0)

##### 5. Conversions Dataset

In [20]:
conversions.head()

,conv_id,lead_id,campaign_id,conversion_date,conversion_type,revenue_idr,cac_idr
0,CNV001,LED00499,CAM0428,2022-06-11,signup,5451903,317386
1,CNV002,LED01052,CAM0439,2023-08-06,form_fill,612186,106661
2,CNV003,LED00867,CAM0085,2024-07-31,purchase,1532902,438084
3,CNV004,LED02001,CAM0016,2022-06-21,signup,4024753,354574
4,CNV005,LED01429,CAM0481,2024-05-17,purchase,8447757,81087

In [21]:
conversions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   conv_id          400 non-null    object
 1   lead_id          400 non-null    object
 2   campaign_id      400 non-null    object
 3   conversion_date  400 non-null    object
 4   conversion_type  400 non-null    object
 5   revenue_idr      400 non-null    int64
 6   cac_idr          400 non-null    int64
dtypes: int64(2), object(5)
memory usage: 22.0+ KB

In [22]:
conversions.isnull().sum()

conv_id            0
lead_id            0
campaign_id        0
conversion_date    0
conversion_type    0
revenue_idr        0
cac_idr            0
dtype: int64

In [23]:
conversions.duplicated().sum()

np.int64(0)